### ISSUE TITLE
OnCallback error

### ISSUE THREAD

**Issue by cbetech** [amir20/phantomjs-node#292]
When I try to use page.set('onCallback',callback) it works fine, but in the documentation http://phantomjs.org/api/webpage/handler/on-callback.html says that i can return data to the html:

```javascript
var webPage = require('webpage');
var page = webPage.create();

page.onCallback = function(data) {
  if (data && data.secret && (data.secret === 'ghostly')) {
    return 'Accepted.';
  }
  return 'DENIED!';
};

(In this component)
page.set('onCallback', function (response) {
 if (data && data.secret && (data.secret === 'ghostly')) {
    return 'Accepted.';
  }
  return 'DENIED!';
});
```
In this component I can't, the return doesnt work, how do I pass data to the html?

Thanks

**Comment by chinchang** [comment]
+1

**Comment by FelixAkk** [comment]
+1

**Comment by amir20** [comment]
Sadly, I haven't fixed this yet in v2 either. Since I have began rewriting for v2, I am open to ideas on how to do this. I don't know of any other phantom clients that have solved this problem.

**Comment by Jezternz** [comment]
Maybe I am fundamentally not understanding how this is supposed to work, I created a very simple example to try describe the problem I am having, I am thinking it is the same as this issue.

```
require('phantom')
	.create()
	.then(function(ph)
	{
		return new Promise(function(resolve, reject)
		{
			ph.createPage().then(function(page)
			{
				page.property('onCallback', function(data) 
				{
					console.log("Data: "+data);
					resolve(data);
					console.log("After");
				});
				page.evaluate(function()
				{
					setTimeout(function()
					{
						window.callPhantom("inside headless browser!");
					}, 1000);
					return;
				});
			});
		});
	})
	.then(function(message)
	{
		console.log("Success! Recieved: "+message);
	});
```

I would expect logging:
```
Data: inside headless browser!
Success! Recieved: inside headless browser!
After
```

but I get only:
`Data: inside headless browser!`

Am I misunderstanding the use of this function, its as if resolve() is called within phantomjs, and if so how do I get a response out? - is that the problem people have described above?

**Comment by amir20** [comment]
@Jezternz Yes you are correct that this is the same problem. What's happening is that `onCallback` is executed in a _different_ process. That process being `phantom`'s process. When you call `resolve()` it doesn't actually run the code you would expect because it is not in node anymore. 

It's really hard to communicate back to Node. You could use #378. I am not sure how I feel about it because it's really a dirty way to do things. 

You really have to understand that phantomjs and node are two different processes and you can't just call code between the two.

**Comment by Jezternz** [comment]
@amir20 Thanks for the explanation, upon further reading I think I understand the obstacles you have to overcome a little better. 

If I understand correctly, it is in phantomjs-node/src/phantom.js line 54, that my message is being printed at.
```
if (message[0] === '>') {
    let json = message.substr(1);
    logger.debug('Parsing: %s', json);
    const command = JSON.parse(json);

    let deferred = this.commands.get(command.id).deferred;
    if (command.error === undefined) {
        deferred.resolve(command.response);
    } else {
        deferred.reject(new Error(command.error));
    }
    this.commands.delete(command.id);
} else {
    logger.info(message); // This is where it is being printed out.
}
```

Would it be possible to hack the first evaluate argument (function), so that we replace:
`window.callPhantom` to be replaced with something like:
```
(function(s)
{ 
    var command = JSON.stringify({ "id": "onCallback", "value": s });
    window.callPhantom("> "+command); 
})
```
This would make method calls such as:
```
    window.callPhantom("inside headless browser!");
    // become:
    (function(s){var command=JSON.stringify({"id":"onCallback","value":s});window.callPhantom("> "+command);})("inside headless browser!");
```
Then create a new command 'onCallback' that would call onCallback listeners? Just an idea, not sure if it would work, I realize would be rather hacky, so may not be preferable?

**Comment by amir20** [comment]
I think sending information over `console.log` is really tricky.  It's really dirty they way you have outlined, because you are trying to communicate back to Node with a message sent with console log. 

What if you do something else. Something like

```js
       page.property('onCallback', function(data) {
                    console.log("Data: "+data);
                    DATA = data;
       });
```

and then use the hack I provided in #378. 
```js

function checkForData(){
  phantom.windowProperty('DATA').then(function(data){
       if(data !== undefined){
             // resolve promise(data)
       }else{
            setTimeout(checkForData, 100); // try again in 100ms to see if the data has been set
       }
 });
```

This works a little better because your are pinging for data. 

I am open to pursuing options that your provided, but it has to be a generic solution that would work for any communication to NodeJs. Yours is very specific to `callPhantom` which scares me. 

Another approach is to do something like this:

```js
page.waitForMessage('fooData').then(function(data){
// got data!
});
```
And then do 
```js
page.property('onCallback', function(data) {
                    console.log("Data: "+data);
                    sendMessage('fooData', data);
       });
```

This last option is obviously the cleanest way to do it. But it's adding a lot of complexity which I don't know if it's worth doing. :/ 

Either way, you would have to probably send me a pull request since I won't have time do it. 

Good luck!

**Comment by Jezternz** [comment]
@amir20 Thanks for all the help, I like the way you have coded this module - very readable, the way good code should be!

**Comment by amir20** [comment]
@Jezternz You're welcome. I am glad you like it!

**Comment by koustuvsinha** [comment]
hi @amir20 ! I have the same query : I am testing some websocket response using Phantom, and I want to quit the testing once the data is received. using the `window.callPhantom` I am communicating that my tasks are done, but in onCallback property this is not working (console.log part is working though) : 

```js
_page.property('onCallback', function (data) {
    console.log('Received response : ' + data.payload)
  _page.close()      // not working
  _ph.exit()             // not working
  })
```

I have even put in a simple function call from there but its not working as well. From your comments it seems it has to do with separate process for PhantomJS and Node. any way I can bypass it?

**Comment by amir20** [comment]
I haven't been able to find a solution. Open to ideas though.

**Comment by enjoythelive1** [comment]
I made a pull request that must solve all the event problems. I did it because i needed a better way to detect the events in phantomjs. Hope you find it useful guys, and also if it is included in the main repo, my package.json would thank you @amir20 

https://github.com/amir20/phantomjs-node/pull/454

**Comment by amir20** [comment]
Closing this as #454 looks to have fixed this. /cc @cbetech

**Comment by pos1tron** [comment]
I might be missing something, but I am still unable to return data to the front end using the onCallback event:

Node process:
```
page.on('onCallback', () => {
  return 'stuff';
});
```

Client Side:
```
var data = window.callPhantom();
console.log(data) // --> null
```

**Comment by amir20** [comment]
Perhaps `page.on('onCallback', ...)` not working is a bug. I don't think I have ever tried that.

**Comment by Attrash-Islam** [comment]
I wrote something based on this library that communicate through bridge file
https://github.com/Attrash-Islam/phantom-tasker (Not completed yet)
