### ISSUE TITLE
invalid: sockjs-client@0.0.0-unreleasable

### ISSUE THREAD

**Issue by jonstorer** [amir20/phantomjs-node#306]
*Remove or Update sockjs-client to a releasable version*

 [app]/node_modules/phantom/node_modules/shoe/node_modules/sockjs-client

`sockjs-client` has always caused an error when `npm shrinkwrap --dev`-ing dependencies. `npm prune` @0.10.26 had been able to remove it. However, @2.14.0 does not remove `sockjs-client`. I realize npm changed, but why include a module that's unreleasable?

**Comment by jonstorer** [comment]
Closing because it's not your problem, it's `shoe`'s problem

**Comment by donaldpipowitch** [comment]
@amir20 I have this problem since updating to `0.8.0`.

**Comment by bradleyayers** [comment]
@donaldpipowitch which old version works? I'm blocked by this issue.

**Comment by donaldpipowitch** [comment]
I use `0.7.2` now.

@amir20 Do we want to re-open this issue? It is somewhat closely related to `phantomjs-node` when it uses a faulty dependency.

**Comment by amir20** [comment]
I reopened the issue. Do we know what causes this? I haven't had a chance to jump in code recently so I am hoping someone else can take a look and issue a `0.8.1` fix

**Comment by PrototypeAlex** [comment]
It's the bundledDeps in shoe https://github.com/substack/shoe/blob/master/package.json#L13 that causes this, after a bit of messing around it appears to be a problem in npm itself.

I can replicate this issue when using npm@2.14.4, but back at npm@2.7.4 it's not a problem, and installs/shrinkwraps fine.

It's also fixed on npm@3.3.7, so that's a win.

**Comment by amir20** [comment]
Probably not going to fix this with v1. But should be fixed with 2.0.0-alpha.
