### ISSUE TITLE
No longer able to use phantom 2

### ISSUE THREAD

**Issue by jrust** [amir20/phantomjs-node#368]
### Expected behavior

To be able to specify the path to phantomjs with the `binary: /path/to/phantomj2` option.

### Actual behavior

Since issue #355 that is no longer possible because it always uses the version of phantomjs installed by this package and ignores any custom `binary` property.

### Steps to reproduce the behavior

1. [This script](https://gist.github.com/dmmmdfll/dcaa99040717e8b5a405), from #349, demonstrates using the binary option and it no longer has any effect.

**Comment by amir20** [comment]
`phantomjs-prebuilt` will use the system phantomjs if the right version is installed, or install the right version if it is not. Right now, it uses phantomjs `v2.1.4`.

I rather keep the phantomjs version tightly coupled to `phantom-node` because that's how the only way I can make sure all specs work. Older versions of phantomjs might not be compatible. In fact, I know they might not be because `sysin` behaves differently in < v2.

With that said, what is your use case? Why do you need to switch versions? I think it makes sense to always support the latest and greatest because `phantomjs-prebuilt` will install it. Maybe you can convince me otherwise.

**Comment by amir20** [comment]
Also, this is not related to #355. In v2, it's completely different.

**Comment by jrust** [comment]
I should have clarified that I am using phantomjs-node v 1.0.0.  I didn't think it safe to upgrade to the latest since it is in alpha.  So, in my project I have Right now in my project I have phantomjs-prebuilt installing version 2.1.4 of phantom, but this code seems to make it so that the version from phantomjs-node is used:
```javascript
    if require('phantomjs').path?
       options.binary = require('phantomjs').path
     else 
       options.path ?= ''
       options.binary ?= options.path+'phantomjs'
```

**Comment by amir20** [comment]
Oh I didn't know you were talking about 1.0.0. I suggest going back to `0.9.0`. I didn't write version 1 so I am only supporting it. v2 is faster and probably going to be supported more.

**Comment by amir20** [comment]
@jrust I will probably GA 2.0.0 tomorrow. I found two bugs and fixed them. I think it is stable now.
