### ISSUE TITLE
Asynchronous actions on a loaded page

### ISSUE THREAD

**Issue by jammi** [amir20/phantomjs-node#452]
Hi, how are asynchronous actions on pages supposed to work?

Let's say I load a page, have phantom click on an element and then wait for a result, then click something else, wait for a result and so forth.

**Comment by amir20** [comment]
Not sure if I understand your question. But this is just a wrapper around phantomjs. You could use `sendEvent` and then check for a status until it is true.

**Comment by amir20** [comment]
Issues are for bugs, where expected behavior is different than actual. For questions or best practices please use other sources like stackoverflow.com. Please review the [guidelines](https://github.com/amir20/phantomjs-node/blob/master/.github/CONTRIBUTING.md) for creating issues before opening new issues in the future.
