### ISSUE TITLE
Working of the phantom js module in linux environment

### ISSUE THREAD

**Issue by ganeshkcs** [amir20/phantomjs-node#456]
Please let me know whether this node package will work for linux environment. If yes, please let me know the configuration steps.

**Comment by amir20** [comment]
You can see this docker file. 

```
FROM ubuntu:15.10
MAINTAINER Amir Raminfar <findamir@gmail.com>

RUN apt-get update && apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_5.x | bash -
RUN apt-get install -y nodejs build-essential g++ flex bison gperf ruby perl \
  libsqlite3-dev libfontconfig1-dev libicu-dev libfreetype6 libssl-dev \
  libpng-dev libjpeg-dev python libx11-dev libxext-dev

RUN npm install phantom co

COPY simple.js simple.js
```

You should look at steps for installing phantomjs.

**Comment by amir20** [comment]
Issues are for bugs, where expected behavior is different than actual. For questions or best practices please use other sources like stackoverflow.com. Please review the [guidelines](https://github.com/amir20/phantomjs-node/blob/master/.github/CONTRIBUTING.md) for creating issues before opening new issues in the future.
