### ISSUE TITLE
self.page.property("onConsoleMessage") interaction with original context

### ISSUE THREAD

**Issue by Whitebeard86** [amir20/phantomjs-node#458]
I'm trying to perform actions based on the page console output, but it seems that the function executed on self.page.property("onConsoleMessage") runs on a different context so I can't access my class variables/functions.

Is there any other way to get the page console information? I can't find any documentation regarding that issue.

Thanks..

**Comment by amir20** [comment]
This is discussed in the documentation. You would want to use `#on(...)` instead. There was a pull request that recently added this feature.

**Comment by amir20** [comment]
Issues are for bugs, where expected behavior is different than actual. For questions or best practices please use other sources like stackoverflow.com. Please review the [guidelines](https://github.com/amir20/phantomjs-node/blob/master/.github/CONTRIBUTING.md) for creating issues before opening new issues in the future.
