### ISSUE TITLE
Ignore signals

### ISSUE THREAD

**Issue by tasoss** [amir20/phantomjs-node#461]
Hello.Is it possible to ignore for example SIGQUIT on the phantom process that is created?
Thanks!

**Comment by amir20** [comment]
I am not sure what means. I just added a slack badge so that i can start chatting about that online instead of creating issues. Try joining that.

**Comment by amir20** [comment]
Issues are for bugs, where expected behavior is different than actual. For questions or best practices please use other sources like stackoverflow.com or the [slack](https://phantomjs-node.herokuapp.com) chat room. 
Please review the [guidelines](https://github.com/amir20/phantomjs-node/blob/master/.github/CONTRIBUTING.md) for creating issues before opening new issues in the future.
