### ISSUE TITLE
Evaluating XMLHttpRequest script

### ISSUE THREAD

**Issue by JakubSK** [amir20/phantomjs-node#462]
Prior to version 2.0, my JavaScript executed by the `evaluate()` function had no issues whatsoever (code below). Ever since upgrading, I now receive errors when calling the same exact code.

I've tried various things such as setting the *async* parameter on `open()` to `true`, but that didn't seem to help...

```javascript
var xhr = new XMLHttpRequest();
xhr.open("GET", myUrl, false);
xhr.responseType = 'arraybuffer';
var bin = xhr.response;
var u8 = new Uint8Array(bin), ic = u8.length, bs = [];
while (ic--) {
	bs[ic] = String.fromCharCode(u8[ic]);
}
resource.data = bs.join('');
```

The error I receive:

```json
Error: {
    "code":15,
    "message":"InvalidAccessError: DOM Exception 15",
    "name":"InvalidAccessError",
    "stack":"anonymous\n\nglobal code\nevaluateJavaScript@[native code]\nevaluate@phantomjs://platform/webpage.js:390:39\nexecuteCommand@phantomjs://code/shim.js:152:44\nread@phantomjs://code/shim.js:115:27",
    "line":22
}
```

**Comment by amir20** [comment]
Can you paste the whole example in v1 and v2? I am not sure where you are trying to do that. So I am not clear.

**Comment by JakubSK** [comment]
This JavaScript is exactly the same for both versions; besides using promises versus a callback of course.

```javascript
page.evaluate(function(myUrl){
    var resource = {};
    var xhr = new XMLHttpRequest();
    xhr.open("GET", myUrl, false);
    xhr.responseType = 'arraybuffer';
    var bin = xhr.response;
    var u8 = new Uint8Array(bin), ic = u8.length, bs = [];
    while (ic--) {
        bs[ic] = String.fromCharCode(u8[ic]);
    }
    resource.data = bs.join('');
    //...
    return resource;
}, url).then(function(result){ /**/ });
```

**Comment by amir20** [comment]
Hmm. I am not really sure. I can't think of anything that can be breaking this. `resource` needs to be serialized to JSON. So maybe something wrong there. Also does this work in vanilla phantomjs? Because I seem to get `undefined` in phantomjs with `String.fromCharCode`. 

Maybe get on Slack to talk about this.

**Comment by amir20** [comment]
Maybe related to https://github.com/ariya/phantomjs/issues/11172

**Comment by JakubSK** [comment]
It looks like this has to do with explicitly setting the `responseType="arraybuffer"` on the `XMLHttpRequest `object when making the call **synchronous**. An exception is thrown according to the [XMLHttpRequest spec](http://www.w3.org/TR/XMLHttpRequest/#the-responsetype-attribute). Unfortunately this breaks my code and I can't figure out a workaround... Would an **asynchronous** `XMLHttpRequest#open()` call be possible with this phantom module and `evaluate()`?

**Comment by amir20** [comment]
This hasn't been done before. But since there is a new method that let's  you have callbacks in node it might be possible. You'd want to add `onCallback` to this file https://github.com/amir20/phantomjs-node/pull/454/files#diff-ec822a34e902804f64cc4f4d376aabd9R13 and try doing something like http://phantomjs.org/api/webpage/handler/on-callback.html. Theoretically it should work. I am on slack today so if you get on I might be able to point to other directions.

**Comment by amir20** [comment]
@JakubSK there is a slack for this project and you can join on http://phantomjs-node.herokuapp.com/ or by clicking the link on the README file at top.
