### ISSUE TITLE
Loading ajax/js Question

### ISSUE THREAD

**Issue by ToruHyuga** [amir20/phantomjs-node#467]
Hello, how to wait a JS request on the page before getting content of page? For crawling some elements which are loading from website server ?

**Comment by amir20** [comment]
Look in the issues. There is `waitUntil` which has been discussed a lot. Also generally try to not ask "How To" questions.

**Comment by amir20** [comment]
Issues are for bugs, where expected behavior is different than actual. For questions or best practices please use other sources like stackoverflow.com or the [slack](https://phantomjs-node.herokuapp.com) chat room. 
Please review the [guidelines](https://github.com/amir20/phantomjs-node/blob/master/.github/CONTRIBUTING.md) for creating issues before opening new issues in the future.
