### ISSUE TITLE
async/await page.evaluate - what is wrong?

### ISSUE THREAD

**Issue by vinnitu** [amir20/phantomjs-node#486]
```javascript
let html = await page.evaluate( => return document.getElementById('body').innerHTML);
```

**Comment by amir20** [comment]
Not the place to ask this question. Please read the guidelines before opening issues.

**Comment by amir20** [comment]
Issues are for bugs, where expected behavior is different than actual. For questions or best practices please use other sources like stackoverflow.com or the [slack](https://phantomjs-node.herokuapp.com) chat room. 
Please review the [guidelines](https://github.com/amir20/phantomjs-node/blob/master/.github/CONTRIBUTING.md) for creating issues before opening new issues in the future. 

This message is a saved reply and was posted automatically.
