### ISSUE TITLE
Is there any way to catch errors when phantomjs crashes? 

### ISSUE THREAD

**Issue by gokulk94** [amir20/phantomjs-node#492]
I am using multiple phantomjs instances to crawl an angular app. But I am getting the following error,
```
error: PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.
```
What I need is to catch this error in my crawl script so that I could skip that URL and move to the next.
Is there any way to do that?

### Expected behavior

`phantom.create()` should throw an error when phantomjs crashes.

### Actual behavior

No errors are thrown. 

### Environment

- OS: Ubuntu 14.4
- Node version (`node -v`): 4.4.4
- package version: 2.1.9

**Comment by amir20** [comment]
Is the error actually coming from `create()` method? That method doesn't communicate with phantom so I am wondering how it would throw that error. 

In [shim.js](https://github.com/amir20/phantomjs-node/blob/master/src/shim.js#L138), there is a `try-catch` method that catches all errors. So if phantomjs throws it in that block, I can catch it. But if the error is `PhantomJS has crashed` then I don't think there is anything I can do unless node can handle it in the process error. 

Can you provide more detail to exactly where this error is thrown?

**Comment by gokulk94** [comment]
No. The error is entirely coming from phantomjs. 
Basically what I am doing is crawl the angular app recursively for URL and open it in phantomjs browser. I'm using async.queue to pipeline this task. callback for the queue is called only after I open the page in phantomjs. So whenever phantomjs crashes, the task stays in the queue. 
I'm looking for a way to call the callback function whenever the browser crashes.

**Comment by elias-winberg** [comment]
Maybe we should add support for `phantom.onError`?

**Comment by gokulk94** [comment]
@elias-winberg Tried that, no luck.
But this error only occurs like once in a thousand tasks. Any idea why this error occurs?

**Comment by amir20** [comment]
There is probably underlying issues with PhantomJS which is causing this. @gokulk94 The fact that you are seeing `error: PhantomJS has crashed...` means that node does see it and is probably printed with [this](https://github.com/enjoythelive1/phantomjs-node/blob/master/src/phantom.js#L73). Technically what @elias-winberg says is true you should be able to capture it, then grep for `/PhantomJS has crashed/` to see if you should restart. That feels too dirty though. Instead of capturing the error, why don't you think of a different solution. Like for example, in most producer/consumer problems with a queuing system, you want to send back to some kind of `ack` if the result was executed on. If the result times outs, then an `ack` is never sent and the item is restored on the queue. You basically need to have a set of workers and when one fails, respawn it. If the phantomjs process is down, it should fail when trying to execute a command, so that would be your way of respawning. Here is something I googled that might be an example to you https://devcenter.heroku.com/articles/asynchronous-web-worker-model-using-rabbitmq-in-node. 

I think you should assume that things can break and defensive code around it. My example above would catch any error and probably scale in the long term.

**Comment by amir20** [comment]
I found this https://github.com/ariya/phantomjs/issues/13581 which probably means that there might be a memory leak. I think your best option is to restart phantomjs after each page.

**Comment by gokulk94** [comment]
I forgot to close the page after I'm done with it, currently exiting the phantom instance. I think this might be the issue. I'm currently running the crawler. As of now, no issue.
