### ISSUE TITLE
can i use jquery in phantomjs-node

### ISSUE THREAD

**Issue by JimShawn** [amir20/phantomjs-node#494]
i use page.includeJs("./jquery.js").then(function(){
       console.log(11);
})
but it didn't work out fine,please help me

**Comment by amir20** [comment]
Issues are for bugs, where expected behavior is different than actual. For questions or best practices please use other sources like stackoverflow.com. 
Please review the [guidelines](https://github.com/amir20/phantomjs-node/blob/master/.github/CONTRIBUTING.md) for creating issues before opening new issues in the future. 

This message is a saved reply and was posted automatically.
