### ISSUE TITLE
Get the type of open pages (images, video, html, json)

### ISSUE THREAD

**Issue by accncc** [amir20/phantomjs-node#498]
### Expected behavior

When you open a link, I do not know that there will be a website or just a picture or video, and so on ... How can I Polic type of open links? (Picture, video, html)?

### Actual behavior

[Describe observed behavior here]

### Steps to reproduce the behavior

1. [First Step]
2. [Second Step]
3. [Other Steps...]

### Environment

- OS:
- Node version (`node -v`):
- package version:

**Comment by amir20** [comment]
What?

**Comment by accncc** [comment]
how to get the type of open links?

**Comment by amir20** [comment]
That's probably a better question for phantomjs. Going to close since it's not related to this.

**Comment by amir20** [comment]
Issues are for bugs, where expected behavior is different than actual. For questions or best practices please use other sources like stackoverflow.com. 

Please review the [guidelines](https://github.com/amir20/phantomjs-node/blob/master/.github/CONTRIBUTING.md) for creating issues before opening new issues in the future. 

This message is a saved reply and was posted automatically.
