### ISSUE TITLE
out_obj.js example is loading partial resources list

### ISSUE THREAD

**Issue by liorg2** [amir20/phantomjs-node#542]
i was expected (I would like) to see the full resources list until the page is fully loaded)

[Describe expected behavior here]

### Actual behavior

[Describe observed behavior here]

### Steps to reproduce the behavior

1. [First Step]
2. [Second Step]
3. [Other Steps...]

Ubuntu

- OS:
- Node version (`node -v`): 6.4.0
- package version:

**Comment by amir20** [comment]
I have no idea what you mean.

**Comment by amir20** [comment]
Issues are for bugs, where expected behavior is different than actual. For questions or best practices please use other sources like stackoverflow.com. 
Please review the [guidelines](https://github.com/amir20/phantomjs-node/blob/master/.github/CONTRIBUTING.md) for creating issues before opening new issues in the future. 

This message is a saved reply and was posted automatically.
