### ISSUE TITLE
Problem with f module

### ISSUE THREAD

**Issue by uragecz** [amir20/phantomjs-node#594]
After installing of phantom, and imported via `const phantom = require('phantom');` i am getting error 

`Uncaught Error:  webpack:///./~/phantomjs-prebuilt/lib/phantomjs.js?:8  Cannot find module "fs`"

Any tips ?

**Comment by KpjComp** [comment]
Your trying to compile using webpack, webpack is normally for client side javascript, phantomjs is Serverside..

**Comment by amir20** [comment]
Issues are for bugs, where expected behavior is different than actual. For questions or best practices please use other sources like stackoverflow.com. 
Please review the [guidelines](https://github.com/amir20/phantomjs-node/blob/master/.github/CONTRIBUTING.md) for creating issues before opening new issues in the future. 

This message is a saved reply and was posted automatically.
