### ISSUE TITLE
Click Example

### ISSUE THREAD

**Issue by TheJimFactor** [amir20/phantomjs-node#595]
Is there an example using this library to click an element and then get the URL that the click kicked off?

For example clicking an element with an onclick event that kicks off a request to save a file to disk, I'd like to get that request URL so I can download that file manually.

The page I'm working on is built with react and the data is available in an obscure, unordered JSON request, and I'd rather just do it via browser automation.

When I've tried to do clicks with this library before it ended up with out of memory errors, so I'm sure I'm doing something wrong.

**Comment by amir20** [comment]
Can you share what you tried? I don't have something handy, maybe others do. But generally, whatever phantomjs documentation says can be followed here.

**Comment by amir20** [comment]
Issues are for bugs, where expected behavior is different than actual. For questions or best practices please use other sources like stackoverflow.com. 
Please review the [guidelines](https://github.com/amir20/phantomjs-node/blob/master/.github/CONTRIBUTING.md) for creating issues before opening new issues in the future. 

This message is a saved reply and was posted automatically.
