### ISSUE TITLE
login with an certificate.pfx

### ISSUE THREAD

**Issue by FernandoGOT** [amir20/phantomjs-node#603]
I want to login in a page that have need to submit an .pfx certificate, but the server ask the certificate before the page load. Is there a way to do it?

**Comment by amir20** [comment]
This is not a bug. Sounds like you need help on how to do something. Please  user other resources.

**Comment by amir20** [comment]
Issues are for bugs, where expected behavior is different than actual. For questions or best practices please use other sources like stackoverflow.com. 
Please review the [guidelines](https://github.com/amir20/phantomjs-node/blob/master/.github/CONTRIBUTING.md) for creating issues before opening new issues in the future. 

This message is a saved reply and was posted automatically.
