### ISSUE TITLE
Registering SIGINT handler to cleanly exit application doesn't work because phantom gets killed right away

### ISSUE THREAD

**Issue by rightaway** [amir20/phantomjs-node#605]
In my application I've done `process.on('SIGINT', mySigintHandler)` to cleanly exit the application when the current tasks have finished rather than killing the application immediately and leaving the tasks in an inconsistent state.

However, as soon as I do `ctrl+c` in the console, the application doesn't cleanly exit because phantomjs is killed right away (error message for example is `Error reading from stdin: Error: This socket has been ended by the other party`).

How can I disable the automatic terminating of phantomjs processes so that I can kill them from my SIGINT handler? This would be a useful feature to add if it's not possible currently.

**Comment by amir20** [comment]
@rightaway it looks like that is done [here](https://github.com/amir20/phantomjs-node/blob/master/src/phantom.js#L157). There is no configuration to disable this. I don't think anybody has ever asked for such need. 

I am curious if you can patch `kill` since it is public by doing `phantomInstance.kill = function(){ ...}`  that's obviously a hack. If it doesn't work, it would make more sense to create a patch that accepts a configuration for this setting.

**Comment by rightaway** [comment]
I'll see if patching `kill` as you suggested works. But how would I clean up the numerous phantom instances that might be alive from my SIGINT handler when the app is ready to cleanly shutdown? Is there a function I can call in this module that would kill all processes? Or would I need to 'unpatch' `kill` before doing this?

**Comment by amir20** [comment]
Each phantom process is managed by one phantom instance. If you create multiple instances then there will be multiple processes. They don't have knowledge of each other. You would have to track the processes yourself and call `.kill()`.

**Comment by rightaway** [comment]
Maybe I'm not understanding, but if you're suggesting I patch `kill` so that the process doesn't get killed, then I can't call `kill` to actually kill it.

**Comment by amir20** [comment]
You are right. You have to save the old function like. Something like: 

```js
phantomInstance.oldKill = phantomInstance.kill;
phantomInstance.kill = function (){
...
}
phantomInstance.oldKill() // will actually kill it. 
```

Ps. This is all monkey patching. A pull request is still a good option. But it would be much harder because you'd have to add tests and read through the code. Up to you which on you do.

**Comment by amir20** [comment]
@rightaway did it work?

**Comment by rightaway** [comment]
@amir20 I decided to work around having to use phantom in this particular case to avoid the monkey patching option. I've been looking through the code to figure out how to create a patch to add configuration to disable automatic termination, but felt fairly lost in the code.

Would you mind re-opening this issue? I do think it's a worthwhile feature request and in the future me or another contributor may have a patch to offer.

**Comment by amir20** [comment]
Generally, I'd like to keep issues open that are actually bugs. Issues should be actionable. If a behavior as not as expected then it is a bug. Feature requests being open will just get lost and no one will ever look at it. No one has asked for this feature so I doubt it will get a PR. If you want it, then it would be you sending the PR. 

The work should be easy. You need to modify the [constructor](https://github.com/amir20/phantomjs-node/blob/master/src/phantom.js#L56) to have some sort of flag to disable the kill. There isn't that much code. Maybe because it uses Flowjs it is confusing.
