### ISSUE TITLE
Error: Error reading from stdin: Error: write EPIPE"

### ISSUE THREAD

**Issue by hacke2** [amir20/phantomjs-node#649]
### Expected behavior

I want to  run a phantom by url route when a pass a query

- ph created
- page created
- page opened: success

ex.:

```js
exports.index = function* () {
  const url = this.query.url;

  if (urlReg.test(url)) {
    const instance = yield phantom.create();
    const page = yield instance.createPage();

    const status = yield page.open('https://stackoverflow.com/');
    console.log(status);

    const content = yield page.property('content');
    console.log(content);

    yield instance.exit();
    this.data = status;
  } else {
    this.data = null;
  }
};
```

### Actual behavior

it throw a error:

```
Error: Error reading from stdin: Error: write EPIPE at Phantom._rejectAllCommands (/home/nemo/local/uae_agent/apps/catchJsError/node_modules/phantom/lib/phantom.js:357:41) at Phantom.kill (/home/nemo/local/uae_agent/apps/catchJsError/node_modules/phantom/lib/phantom.js:337:14) at Socket.Phantom.process.stdin.on.e (/home/nemo/local/uae_agent/apps/catchJsError/node_modules/phantom/lib/phantom.js:175:18) at emitOne (events.js:96:13) at Socket.emit (events.js:188:7) at onwriteError (_stream_writable.js:318:10) at onwrite (_stream_writable.js:336:5) at WritableState.onwrite (_stream_writable.js:89:5) at fireErrorCallbacks (net.js:455:13) at Socket._destroy (net.js:496:3)
```

### Environment

- OS:  6.0.0
- Node version (`node -v`): linux
- package version: 4.0.2

**Comment by amir20** [comment]
I don't understand what your problem is or what is causing it. I can't reproduce it. Can you provide something I can run locally? A way to reproduce it would be nice.

**Comment by amir20** [comment]
Closing this ticket because there has been no response. We can reopen if needed.

**Comment by oxygens** [comment]
SSH login into fresh CentOS 7 install, using Putty.

Just trying to open a simple page (works on Windows).

```
[1555] Unhandled Rejection at: Promise Promise {
  <rejected> Error: Error reading from stdin: Error: write EPIPE
    at Phantom._rejectAllCommands (/jsonrpc-bidirectional/node_modules/phantom/lib/phantom.js:357:41)
    at Phantom.kill (/jsonrpc-bidirectional/node_modules/phantom/lib/phantom.js:337:14)
    at Socket.Phantom.process.stdin.on.e (/jsonrpc-bidirectional/node_modules/phantom/lib/phantom.js:175:18)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at onwriteError (_stream_writable.js:341:10)
    at onwrite (_stream_writable.js:359:5)
    at fireErrorCallbacks (net.js:480:13)
    at Socket._destroy (net.js:521:3)
    at WriteWrap.afterWrite [as oncomplete] (net.js:815:10) } reason Error: Error reading from stdin: Error: write EPIPE
    at Phantom._rejectAllCommands (/jsonrpc-bidirectional/node_modules/phantom/lib/phantom.js:357:41)
    at Phantom.kill (/jsonrpc-bidirectional/node_modules/phantom/lib/phantom.js:337:14)
    at Socket.Phantom.process.stdin.on.e (/jsonrpc-bidirectional/node_modules/phantom/lib/phantom.js:175:18)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at onwriteError (_stream_writable.js:341:10)
    at onwrite (_stream_writable.js:359:5)
    at fireErrorCallbacks (net.js:480:13)
    at Socket._destroy (net.js:521:3)
    at WriteWrap.afterWrite [as oncomplete] (net.js:815:10)
```

Node.js v7.9.0

Reproduce using:
```shell
git clone git@github.com:oxygens/jsonrpc-bidirectional.git jsonrpc-bidirectional
cd jsonrpc-bidirectional
npm install
node --expose-gc --max-old-space-size=3072 tests/bug_uws_close_await_hang.js
```

Basically, this reproduces the issue for me:
```JavaScript
const Phantom = require("phantom");

(async ()=>{
	const phantom = await Phantom.create(
		[],
		{
			logger: console,
			logLevel: "error" // error | debug
		}
	);

	const phantomPage = await phantom.createPage();
	await phantomPage.setting("javascriptEnabled", true);

	const strPhatomPageURL = "https://google.com";
	await phantomPage.open(strPhatomPageURL);
})();
```

**Comment by oxygens** [comment]
These people have the same issue since apr 2015:

[https://github.com/marcbachmann/node-html-pdf/issues/35](https://github.com/marcbachmann/node-html-pdf/issues/35)

**Comment by amir20** [comment]
Did you try `npm rebuild phantomjs-prebuilt`?

**Comment by amir20** [comment]
I tried running jsonrpc example and I get

```
[54689] Unhandled Rejection at: Promise Promise {
  <rejected> ReferenceError: phantomPage is not defined
    at AllTests.callRPCMethodFromWebPage (/Users/amirraminfar/Desktop/jsonrpc-bidirectional/tests/AllTests.js:1029:9)
    at process._tickCallback (internal/process/next_tick.js:109:7) } reason ReferenceError: phantomPage is not defined
    at AllTests.callRPCMethodFromWebPage (/Users/amirraminfar/Desktop/jsonrpc-bidirectional/tests/AllTests.js:1029:9)
    at process._tickCallback (internal/process/next_tick.js:109:7)
``` 

instead. 

I then tried running `await phantomPage.open("https://google.com");` on my mac with your test and it worked. 

I have a feeling this is an env issue with linux. Have you tried running without node to see how phantomjs behaves? That's probably the eaisest way to debug.

**Comment by oxygens** [comment]
```
[root@vm bin]# ./phantomjs
./phantomjs: error while loading shared libraries: libfontconfig.so.1: cannot open shared object file: No such file or directory
[root@vm bin]# pwd
/test/node_modules/phantomjs-prebuilt/lib/phantom/bin
```

**Comment by amir20** [comment]
@oxygens I tried running within centos7 via docker and I got a bunch of different errors when trying to install `phantomjs-prebuilt`. Then I tried to install phantomjs in centos and noticed that also broke. I was confused but found that bzip2 and bzip2-libs libs are not installed. I installed those using `yum` and was able to get phantomjs running. I was then able to run `npm i phantom` which worked and then run `node test.js` (from above) which worked.

**Comment by amir20** [comment]
@oxygens see my above answer.

**Comment by oxygens** [comment]
To fix my error:
```
yum install libXext  libXrender  fontconfig  libfontconfig.so.1
```

Isn't there a phantom build without dependencies?

**Comment by amir20** [comment]
phantom tries installing `phantomjs-prebuilt` _if_ it's not already installed. It's not smart enough to realize you don't have all dependencies. You should make phantomjs worked before using `phantom`.

**Comment by amir20** [comment]
Also I recommend reading http://phantomjs.org/build.html and installing all those dependencies.

**Comment by oxygens** [comment]
I think you need to fix your library to properly throw the right error (which phantom has sent to stderr or stdout) before trying to open the pipes (which close immediately cause the process exits).

Otherwise anyone using your library in any project, will have no idea what is going on, when installing on some fresh Linux box.

**Comment by amir20** [comment]
> I think you need to fix your library to properly throw the right error (which phantom has sent to stderr or stdout) before trying to open the pipes (which close immediately cause the process exits).

Pull requests are welcome @oxygens. 

You are the first person who has ran to this problem. I think if you had paid attention to the actual output like I did then you could have avoided this problem. :)

**Comment by oxygens** [comment]
This is not my bug report, it is somebody else's, and it is quite an assumption to say I am the only one to run into the problem.

For the moment, I have updated my usage to go out of its and send `phantomjs --help` error output to `stderr`.
```
		try
		{
			phantomPage = await phantom.createPage();
		}
		catch(error)
		{
			if(
				error.message.includes("Error reading from stdin")
				&& os.platform() === "linux"
			)
			{
				// https://github.com/amir20/phantomjs-node/issues/649
				console.error("phantomjs may have reported an error in the phantom library.");
				console.error("If missing phantomjs dependencies: yum install libXext  libXrender  fontconfig  libfontconfig.so.1");

				const processCommand = exec("../node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs --help");
				processCommand.stdout.pipe(process.stdout);
				processCommand.stderr.pipe(process.stderr);
				await new Promise(async (fnResolve, fnReject) => {
					processCommand.on("error", fnReject);
					processCommand.on("exit", (nCode) => {
						if(nCode === 0)
						{
							fnResolve();
						}
						else
						{
							fnReject(new Error("Failed with error code " + nCode));
						}
					});
				});

				process.exit(1);
			}
			
			throw error;
		}
```

The key is this:
```
processCommand.stdout.pipe(process.stdout);
processCommand.stderr.pipe(process.stderr);
```

This way, the phantomjs startup error is not hidden away.

I hope it is useful to you.

**Comment by amir20** [comment]
@oxygens something like this is already implemented [here](https://github.com/amir20/phantomjs-node/blob/master/src/phantom.js#L66). I don't know why that didn't work. Probably because phantomjs-prebuilt installed but it still didn't work correctly without dependencies. 

I did want to say something that has been bothering me. This is an open-source project. It's not "my" library as you wrote. There has been a lot of people contributing. I don't get paid for it and do it mostly out of my free time. If you feel like it can be improved then please send a pull request. I won't have time to fix every issue. It is important to realize this library doesn't replace phantomjs. It is an extension to phantomjs as it proxies everything. If you don't understand how phantomjs works then you shouldn't use this library. I will probably update the README file to make sure others understand that. In the last three years of me answering to all issues, I think you are the only person who had a hard time with centos7. Clearly, if you had read the output during `npm install` then you would has seen the same error that I saw. But instead you seem to be blaming the library. I hope you understand my frustration. With your tone, you are expecting for free open-source projects to work out of the box. 

Instead, send a pull request. Be part of the community that improves the code. I think the right fix is to add something to this [code](https://github.com/amir20/phantomjs-node/blob/master/src/phantom.js#L66) where it tries to do `phantom --version` and throw an `Error` if it didn't work. In the past I had done `processCommand.stdout.pipe(process.stdout)` but then a whole slew of people complained because they wanted to be turned off. A lot of people do cron jobs and complained that they had no control. Perhaps sending it to `logger` is even better. 

Best of luck and glad to see it is working now.

**Comment by oxygens** [comment]
Thank you for all your hard work on this library amir20 :)

I choose to contribute code to projects in which I know my way around so I can be efficient. Otherwise I just contribute a minimum of debugging, time and bug reports.

I hope this thread will be useful to someone.
