### ISSUE TITLE
Not getting all the content even with a big wait.

### ISSUE THREAD

**Issue by magician11** [amir20/phantomjs-node#677]
### Expected behavior

I would like to scrape the movie times and movie listings from this page https://www.sfcinemacity.com/showtime/cinema/9936

I'm using this code:
```
// using phantomjs
const phantom = require('phantom');

const timeout = ms => new Promise(resolve => setTimeout(resolve, ms));

(async function() {
  const instance = await phantom.create();
  const page = await instance.createPage();
  await page.on('onResourceRequested', function(requestData) {
    console.info('Requesting', requestData.url);
  });

  const status = await page.open(
    'https://www.sfcinemacity.com/showtime/cinema/9936'
  );
  console.log(`Status on opening sfcinemacity page: ${status}`);

  await timeout(15000);
  console.log('Waiting 15 seconds..');
  const content = await page.property('content');
  console.log(content);

  await instance.exit();
})();
```

While this does grab a lot of content, things like the movie times are not in the final content. There is a big delay to hopefully ensure all possible JS is run before the HTML is extracted.

### Actual behavior

So piping the console logged data to another file, I don't see any movie times. There should be a class in the HTML called `time-item` attached to each movie time.

### Steps to reproduce the behavior

Run the above code and pipe to a file. e.g. `node phantom.js > test.html`

### Environment

- OS: Mac OS 10.12.4
- Node version v7.9.0
- package version: 4.0.4

What is the best way to grab even the whole source after all the JS is run? Thank you.

**Comment by amir20** [comment]
I was able to reproduce this. One thing I noticed was 

> info: Error: [vuex] vuex requires a Promise polyfill in this browser.

In the error. I am guessing phantomjs doesn't have a polyfill for Promise so nothing is actually being executed. Unfortunately, the solution is out of my scope to help. You'll have to investigate how to fix this. Sorry :(

**Comment by magician11** [comment]
So I don't fully understand. In the examples for this module, Promises are used everywhere it seems. Whether it's a promise chain or using async/await.

Can my code snippet above be re-written using callbacks or something else?

**Comment by amir20** [comment]
I think you are misunderstanding what is happening. Promises are used in nodejs which works fine because node supports promises. The problem is that the page you are trying to test actually uses promises on the web page. The web page gets executed in PhantomJs. PhantomJs dom doesn't support promises natively. Most websites include some kind of polyfill so that old browsers and phantomjs would still work. It doesn't look like `https://www.sfcinemacity.com/showtime/cinema/9936` has that polyfill. So it breaks phantomjs browser. It has nothing to do with this module or the use of promises outside of the page. 

You have to read more about promises and the support of browsers.
