### ISSUE TITLE
how do i access to cookies

### ISSUE THREAD

**Issue by heaplabs** [amir20/phantomjs-node#685]
Need access to cookies from phantom.cookies how do i access them?

**Comment by amir20** [comment]
This has been asked a lot. Read the docs or search the closed issues.

**Comment by amir20** [comment]
Issues are for bugs, where expected behavior is different than actual. For questions or best practices please use other sources like stackoverflow.com. 
Please review the [guidelines](https://github.com/amir20/phantomjs-node/blob/master/.github/CONTRIBUTING.md) for creating issues before opening new issues in the future. 

This message is a saved reply and was posted automatically.
