### ISSUE TITLE
Phantom not working on Heroku

### ISSUE THREAD

**Issue by acanyon** [amir20/phantomjs-node#689]
I'm having trouble getting this to run on heroku. Seams it isn't finding phantomjs in /app/vendors/phantomjs

### Actual behavior

error: Could not spawn [/usr/local/bin/phantomjs] executable. Please make sure phantomjs is installed correctly.
error:  Error: spawn /usr/local/bin/phantomjs ENOENT
    at exports._errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:607:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

### Steps to reproduce the behavior

Run on heroku.

### Environment

- OS: Heroku
- Node version (`node -v`): v8.2.1
- package version: 4.0.5

**Comment by amir20** [comment]
How is phantomjs installed? I haven't used heroku in a while. It worked docker. Are you just using npm to install it?

Sent via my iPhone

**Comment by acanyon** [comment]
I installed it with npm. 

I also used the Heroku build pack to install the base, which exists in the path. https://github.com/stomita/heroku-buildpack-phantomjs

**Comment by amir20** [comment]
Oh I am not familiar with stomita/heroku-buildpack-phantomjs. I can try running a regular node package to see what it does. But I won't be able to do so until late this week. Maybe you can help me look closer. Does `npm i` during the building in heroku throw any errors? Most likely you are not able to build phantomjs because dependencies are missing. And with stomita/heroku-buildpack-phantomjs, if the version phantomjs doesn't match then it will try to reinstall phantomjs. :(

**Comment by acanyon** [comment]
I added `phantom` to `package.json` and it worked! 

Thanks for your time, @amir20!

**Comment by amir20** [comment]
Oh ha. Yea you need `phantom`.
