### ISSUE TITLE
Promise for phantom.create() not working under Grunt

### ISSUE THREAD

**Issue by redaxmedia** [amir20/phantomjs-node#692]
Hello,

I wrote a tiny linter for CSS that works perfect using the CLI or while running the testing suite. At this point I tried to wrap it into a Grunt task but there are issues with the Promise for the phantom.create() method.

### Expected behavior

Fire the then() and return the phantom instance.

### Actual behavior

It doesn't fire the then() or even a catch()  - something is going terrible wrong.

```
phantom
	.create(
	[
		'--load-images=no'
	],
	{
		logLevel: option.get('loglevel')
	})
	.then(currentInstance =>
	{
		instance = currentInstance;
		return instance.createPage();
	});
```
Source: https://github.com/redaxmedia/ncss-linter/blob/master/src/core.js#L281-L285

#### Clone
```
git clone https://github.com/redaxmedia/ncss-linter.git
```
#### Install
```
npm install
```
#### Run
```
bin/cmd.js --url=https://ncss.io --namespace=rs --loglevel=debug
```
#### Screenshot
![grafik](https://user-images.githubusercontent.com/1835397/29147427-450eff3e-7d67-11e7-938c-e21787df6f23.png)

#### Clone
```
git clone https://github.com/redaxmedia/grunt-ncss-linter.git
```
#### Install
```
npm install
```
#### Run
```
grunt
```
#### Screenshot
![grafik](https://user-images.githubusercontent.com/1835397/29147394-f455cc08-7d66-11e7-9c48-16c45cf8ccf7.png)

### Environment

- OS: Ubuntu
- Node version 6.x.x
- package version: 3.x.x

**Comment by amir20** [comment]
First, this is a neat idea. :) 

I can't actually go through all of your code. That's a lot of effort. Could you try to do give me a small example that reproduces this? I know that's probably harder said than done because you don't know where the problem is. 

Have you tried using async and await? That's supported in Node 8+. 

What happens when you add `console.log`s to see what the page object is? 

Last, I don't see a `catch` for the promise that is failing. You should have a `catch` [here](https://github.com/redaxmedia/ncss-linter/blob/master/src/core.js#L313). Of course, if you use `async` then you can `try-catch` everything. :)

**Comment by redaxmedia** [comment]
Thank you for the quick response.

Well, like I describe before: there is no calling of then() and catch() ... adding tons of console.log() does return nothing... I also tried the Node 8 example but this also is not working.

The good news are... I created a repository for testing! :-) You can finde the awesome Node 8 code example inside [tasks/plugin.js](https://github.com/redaxmedia/grunt-phantom-testing/blob/master/tasks/plugin.js#L9-L31) and therefore modify and debug phantom.

#### Clone
```
git clone https://github.com/redaxmedia/grunt-phantom-testing.git
```

#### Install
```
npm install
```

#### Run

```
grunt **(not working)**
```

```
node tasks/plugin.js **(working)**
```

I guess this is a better way to get things resolved.

**Comment by amir20** [comment]
I think I found your problem. I am no grunt expert. But I did some googling and [here](https://gruntjs.com/creating-tasks) suggested to use `this.async()`. So that intrigued my interest. I don't think `async` is supported natively in grunt. Therefore, you have to go back to using `Promise` or transpile to es6 without async. 

Here is what worked at the end

```diff
diff --git a/package.json b/package.json
index eb28d32..92b8e31 100644
--- a/package.json
+++ b/package.json
@@ -3,12 +3,10 @@
 	"description": "Phantom testing for Grunt",
 	"version": "1.0.0",
 	"license": "GPL-3.0",
-	"dependencies":
-	{
+	"dependencies": {
 		"phantom": "4.0.5"
 	},
-	"devDependencies":
-	{
+	"devDependencies": {
 		"grunt": "1.0.1"
 	}
 }
diff --git a/tasks/plugin.js b/tasks/plugin.js
index d95b825..0ceace8 100644
--- a/tasks/plugin.js
+++ b/tasks/plugin.js
@@ -6,28 +6,24 @@ const phantom = require('phantom');
  * @since 1.0.0
  */
 
-function init()
-{
-	(async function(url)
-	{
-		console.log('let me try to open: ' + url);
-		const instance = await phantom.create();
-		console.log('uncomment phantom.create() to show this');
+function init() {
+	var done = this.async();
+
+	phantom.create().then(ph => {
+		_ph = ph;
+		return _ph.createPage();
+	}).then(page => {
+		_page = page;
+		return _page.open('https://google.com/');
+	}).then(status => {
+		return _page.property('content')
+	}).then(content => {
+		console.log(content)		
+		return _ph.exit();
+	}).then(() => {
+		done();
+	}).catch(e => console.log(e));
 
-		const page = await instance.createPage();
-		await page.on("onResourceRequested", function(requestData)
-		{
-			console.info('Requesting', requestData.url)
-		});
-
-		const status = await page.open(url);
-		console.log(status);
-
-		const content = await page.property('content');
-		console.log(content);
-
-		await instance.exit();
-	}('https://google.com'));
 }
 
 /**
@@ -40,11 +36,8 @@ function init()
  * @return object
  */
 
-function construct(grunt)
-{
-	grunt.registerMultiTask('phantom', 'Phantom testing for Grunt', init);
+function construct(grunt) {
+	grunt.registerTask('phantom', 'Phantom testing for Grunt', init);
 }
 
-module.exports = construct;
-
-init();
\ No newline at end of file
+module.exports = construct;
\ No newline at end of file
```

Which seems to work.

<img width="1284" alt="screen shot 2017-08-09 at 6 42 54 pm" src="https://user-images.githubusercontent.com/260667/29150928-971f32ce-7d32-11e7-8e47-d0bfe6ca100a.png">

Ps. Thanks for the clear issue and bug. It makes it so much easier to help. 👍

**Comment by redaxmedia** [comment]
I tried the same at this moment but you were faster.

Thank you very much for your work!
