### ISSUE TITLE
onLoadFinished callback executed before the requested urls are already finished

### ISSUE THREAD

**Issue by mzachariadis** [amir20/phantomjs-node#726]
Hello there !! Congrats for the great work.. I have some problems so I'll try to explain below. 

### Expected behavior

I am using phantomjs-node to render some content. 
The content is already requested using **request** nodejs module. So, I use the page.setContent(body, url) to pass the html body. 
After the setContent execution, I can see the requested urls (js, css etc) through the **onResourceRequested** event. 
By using the **onLoadFinished** event, I try to render the page's content and finally I try to exit() the page instance. 

### Actual behavior

I can see that onLoadFinished callback, executed before all the requested urls are finished. In some webpages this is not a problem but in others (e.g stackoverflow) I get a lot of warnings. Maybe because of Ads loading -> 

> warn: exit() was called before waiting for commands to finish. Make sure you are not calling exit() prematurely.

The rendering looks fine but I wonder if I am doing something wrong. 
I just wanted to create a jpg/pdf screenshot of a webpage, after setContent is finished its execution. So, I used the onLoadFinished event. 

If I use the page.open() method, everything is fine. But, there are specific reasons that I have to use pre-fetched html code. 

### Steps to reproduce the behavior

```
(async function (url, body) {

    const instance = await phantom.create();
    const page = await instance.createPage();
    await page.on('onResourceRequested', function (requestData) {
        console.info('[REQUESTING]', requestData.url);
    });

    page.property('viewportSize', {width: 1280, height: 1024});

    page.on('onLoadFinished', function (status) {
        console.log('onLoadFinished')
        setTimeout(function () {
            onLoadFinished();
        }, 100)
    });

    async function onLoadFinished() {
        page.evaluate(........);

        // rendering
        //........
        //.....

        // filePath and fileOptions are already defined
        var isRendered = await page.render(filePath, fileOptions);
       
        await instance.exit();
    }

    await page.setContent(body, url);
})("http://www.google.com", "<html...../>")
```

### Environment

- OS: Mac OS 10.12.6
- Node version (`node -v`): v8.0.6
- package version: 5.3.0

**Comment by amir20** [comment]
Are you sure about package version `5.3.0`? Because that doesn't exist. 🤣

**Comment by amir20** [comment]
So I have been doing some [research](https://stackoverflow.com/questions/11340038/phantomjs-not-waiting-for-full-page-load).  If I remember correctly, I looked in to this a long time ago and `setContent` and `onLoadFinished` are not compatible. I recall that `onLoadFinished` is basically the same call back as `page.open(url, <callback>)` so passing custom HTML changes this behavior. 

I think the right approach is to wait by calling the popular [waitUntil](https://github.com/amir20/phantomjs-node/issues/431#issuecomment-207865947) function that I wrote a while back and check `document.readyState`.

I don't know of a cleaner approach.  Given all the async stuff going on, i think you'll have to think outside of the box and poll for `state==done`. 

Marking this also as an upstream dependency because it's something that phantomjs should fix.

**Comment by amir20** [comment]
PS. Thank you for the detailed issue. Makes it a lot easier to understand what's going on

**Comment by mzachariadis** [comment]
Thank you very much for the detailed answer. 

I thought that the package version was the **npm version**.. Maybe not!! :p 

Very nice approach using promises to achieve the `state==done` condition. 
I made some tests using your approach and I can see that it's more accurate than the **onLoadFinished** event. 

Thanks again !!
