### ISSUE TITLE
How to keep the “page” variable in the last request for next request

### ISSUE THREAD

**Issue by HTKT** [amir20/phantomjs-node#734]
I using the Phantom NodeJS to open the page. The process of my server as below:

1. Client send request to `/a` endpoint to open the page. At this time, i created 1 instance `phantomInstance` and `page` variable. After finished, Server return the result (here is the captcha image) to Client.
2. Client need to reply the data (captcha text) to `/b` endpoint to verify the captcha with the page which open in the last request `/a`, if success then close and exit phantom.

The issue is:

1. If i declare page variable in global, then another requests (from many clients sent to) will overwrite this variable and my result will be wrong.
2. If i declare `page` in local scope, then i dont know how to reuse the created page variable in the first request.

May i know there're any solution for this problem?
Thanks for helping.

**Comment by amir20** [comment]
@HTKT just store the page variable in a map or array. Like `array['myPage'] = page`. 

You are asking a lot of rudimentary questions though. Please keep issues to bugs. This isn't the place to ask how to code.

**Comment by amir20** [comment]
Issues are for bugs, where expected behavior is different than actual. For questions or best practices please use other sources like stackoverflow.com. 
Please review the [guidelines](https://github.com/amir20/phantomjs-node/blob/master/.github/CONTRIBUTING.md) for creating issues before opening new issues in the future. 

This message is a saved reply and was posted automatically.
