### ISSUE TITLE
How to read js file loaded

### ISSUE THREAD

**Issue by jatinseth2007** [amir20/phantomjs-node#753]
I am loading a webpage and able to see js files loaded, but I need to read content of one of js file loaded on page, how can do it ?

**Comment by amir20** [comment]
This is not a bug. If you provide code then I could help.

**Comment by amir20** [comment]
Issues are for bugs, where expected behavior is different than actual. For questions or best practices please use other sources like stackoverflow.com. 
Please review the [guidelines](https://github.com/amir20/phantomjs-node/blob/master/.github/CONTRIBUTING.md) for creating issues before opening new issues in the future. 

This message is a saved reply and was posted automatically.
