### ISSUE TITLE
Could not spawn [C:\phantom\bin\phantomjs.exe]

### ISSUE THREAD

**Issue by danshmidt77** [amir20/phantomjs-node#781]
### Expected behavior

[Describe expected behavior here]

### Actual behavior

[Describe observed behavior here]

### Steps to reproduce the behavior

1. [First Step]
2. [Second Step]
3. [Other Steps...]

### Environment

- OS:
- Node version (`node -v`):
- package version:

**Comment by danshmidt77** [comment]
Working perfectly without transpiling, however after transpile throws error:
Using webpack with target node.

error: Could not spawn [C:\phantom\bin\phantomjs.exe] executable. Please make sure phantomjs is installed correctly.
error: undefined {"errno":"ENOENT","code":"ENOENT","syscall":"spawn C:\\phantom\\bin\\phantomjs.exe","path":"C:\\phantom\\bin\\phantomjs.exe","spawnargs":["\\\\shim\\index.js\\"]}

**Comment by amir20** [comment]
Does `C:\phantom\bin\phantomjs.exe` exist? I am afraid you are on your own if I can't reproduce this. I am on a mac.

**Comment by amir20** [comment]
Oh sorry. I don't think I understood your problem. There isn't anything stopping you to transpile. I can't imagine what could be the problem because if you look at the source code, it's actually all written in flow and transcompiled to es6. If it is the path, then you can override most of these settings https://github.com/amir20/phantomjs-node/blob/master/src/phantom.js#L64. 

I closed this issue because you didn't follow the template. If you want more help, then provide the answers to the template so that I can reproduce it locally.

**Comment by danshmidt77** [comment]
Good, thank you!
