### ISSUE TITLE
CHANGELOGS feature request

### ISSUE THREAD

**Issue by pabx06** [amir20/phantomjs-node#783]
Hello. 

i have trouble finding the changelogs.
For a project : i am evaluating upgrading from 4.0.12 to 6.0.3. And i don't have any test unit yet for testing regressions.

i would be happy i some one could point me out to a changelog. Thanks.

**Comment by amir20** [comment]
@pabx06 I used to have CHANGELOGS but ended up removing them because nothing major was added except bug fixes. It seemed like `git log` did what I needed as well. Have you tried doing a `compare` in github? 

https://github.com/amir20/phantomjs-node/compare/v4.0.12...v6.0.3

The most major commit was this refactor https://github.com/amir20/phantomjs-node/pull/742
